### ISSUE TITLE
License of this project

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-3-preview#40]
What will be the License of this project?

**Comment by comountainclimber** [comment]
This is a very good point to bring up... I am totally unfamiliar with software licensing and these sorts of issues do you have any suggestions? @lllwvlvwlll @deanragnarok

**Comment by lllwvlvwlll** [comment]
@vncoelho tentatively, the license will be MIT; we are having a discussion internally about moving to apache2.0 (based on the conversation in shanghai)
