### ISSUE TITLE
The "Main" header navigates to a dead page on expand

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo-3-preview#51]
Clicking to expand the `Main` section of a manifest navigates to a dead page.

Example:
https://neo3-preview.com/contract/0x43cf98eddbe047e198a3e5d57006311442a0ca15

**Comment by comountainclimber** [comment]
https://github.com/CityOfZion/neo-3-preview/commit/e0b9c16db3d0399cb83138b58e81abee524c17b3
